// <auto-generated />
using CoffeeHouse.DAL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoffeeHouse.DAL.Migrations
{
    [DbContext(typeof(CoffeeContext))]
    [Migration("20220722054428_CoffeeHouseMigration")]
    partial class CoffeeHouseMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CoffeeHouse.DAL.Models.CoffeeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<int>("MakeTime")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Temperature")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CoffeeEntity");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cost = 37,
                            MakeTime = 12,
                            Name = "Tom",
                            Temperature = 14
                        },
                        new
                        {
                            Id = 2,
                            Cost = 41,
                            MakeTime = 12,
                            Name = "Bob",
                            Temperature = 14
                        },
                        new
                        {
                            Id = 3,
                            Cost = 24,
                            MakeTime = 12,
                            Name = "Sam",
                            Temperature = 14
                        });
                });

            modelBuilder.Entity("CoffeeHouse.DAL.Models.CupEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<int>("Material")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Volume")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CupEntity");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cost = 10,
                            Material = 123,
                            Name = "Food1",
                            Volume = 22
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
